// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static var instance;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBk6nmag4OTQdHwWjRrsWFv4rOS38bFc',
    appId: '1:804798152066:web:a9f6b0eccabeffc918a39b',
    messagingSenderId: '804798152066',
    projectId: 'flutter-login-ui-d7600',
    authDomain: 'flutter-login-ui-d7600.firebaseapp.com',
    storageBucket: 'flutter-login-ui-d7600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuiWAuX5HIgXen0ngDT43_BvjwHeg09G0',
    appId: '1:804798152066:android:196fd21f1d1a90cc18a39b',
    messagingSenderId: '804798152066',
    projectId: 'flutter-login-ui-d7600',
    storageBucket: 'flutter-login-ui-d7600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsC9efpszR2ZNs2VKHvpMPSUreqCH56yU',
    appId: '1:804798152066:ios:b636cccee24d78df18a39b',
    messagingSenderId: '804798152066',
    projectId: 'flutter-login-ui-d7600',
    storageBucket: 'flutter-login-ui-d7600.appspot.com',
    iosClientId:
        '804798152066-adc3bkgdj997jdrcsr8j6vki6ssp700e.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsC9efpszR2ZNs2VKHvpMPSUreqCH56yU',
    appId: '1:804798152066:ios:f41422760d6783d018a39b',
    messagingSenderId: '804798152066',
    projectId: 'flutter-login-ui-d7600',
    storageBucket: 'flutter-login-ui-d7600.appspot.com',
    iosClientId:
        '804798152066-jmoreb53ol9dhlnvr1ja5u7irqstk2pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAuth.RunnerTests',
  );
}
